// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9c622869-1af6-414e-985b-3e0f15390712";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTEMPChange();
void onLED1Change();
void onLED2Change();
void onLED3Change();

float tEMP;
bool lED1;
bool lED2;
bool lED3;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(tEMP, READWRITE, 5 * SECONDS, onTEMPChange);
  ArduinoCloud.addProperty(lED1, READWRITE, ON_CHANGE, onLED1Change);
  ArduinoCloud.addProperty(lED2, READWRITE, ON_CHANGE, onLED2Change);
  ArduinoCloud.addProperty(lED3, READWRITE, ON_CHANGE, onLED3Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
